---
master:
  user: user
  group: group
  host: example.com
  public_dir: "path/to/public/"
  cpchuy_dir: "/home/vagrant/chuy/"
  dbname: name
  dbuser: user
  dbpassword: password
  dbhost: localhost
  exclude: "*.swp"

