---
master:
  user: user
  group: group
  hosts:
      - example.com # DOMAIN OR IP
  public_dir: "path/to/public/"
  cpchuy_dir: "/home/vagrant/chuy/"
  dbname: name
  dbuser: user
  dbpassword: password
  dbhost: localhost
  exclude:
      - "*.swp"

