version: "2.0"

services:
    wordpress:
        build: ./
        hostname: "${PROJECT_NAME}_wordpress"
        container_name: "${PROJECT_NAME}_wordpress"
        depends_on:
            - db
        ports:
            - "80:80"
        volumes:
            - "./${PROJECT_ROOT}:/var/www/html/wp-content"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
            WORDPRESS_DB_NAME: "${DB_NAME}"
            WORDPRESS_DB_NAME: "${DB_NAME}"
            WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
    db:
        image: mysql
        hostname: "${PROJECT_NAME}_db"
        container_name: "${PROJECT_NAME}_db"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "${PROJECT_NAME}_phpmyadmin"
        ports:
            - 8080:80
        depends_on:
            - db
        environment:
            PMA_HOST: db
volumes:
    db_data:
